name: "cachix"
on:
  push:
    branches:
    - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: trickypr
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}} 
    - run: nix build
    - run: nix build .#docker
    - run: docker load < result
    - run: docker push ghcr.io/trickypr/rin:latest

